---
title: Learning to Use the Shell
subtitle: Moving Towards Text Based Computing
author:
- "Programming Practices for Economics Research"
institute:
- Department of Economics, Univeristy of Zurich
date: Winter 2019
---
