---
title: Introduction to the Shell
subtitle: How to become hackerman in less than 4 hours
author:
- Programming Practices for Economics Research
institute:
- Department of Economics, Univeristy of Zurich
date: Fall 2018
---
