# subworkflow: slides
#
# contributor: @lachlandeer
#
#

# --- Libraries --- #
import os, re

# --- Pandoc version --- #

def get_pdf_engine():
    pandoc_version = os.popen("pandoc --version").read().splitlines()[0]
    version_number = int(re.search('\d', pandoc_version).group(0))
    print('Working with pandoc version:', version_number)
    if version_number < 2:
        pdf_engine  = "--latex-engine=pdflatex"
    else:
        pdf_engine = "--pdf-engine=pdflatex"
    return pdf_engine

PDF_ENGINE = get_pdf_engine()

## --- Set up Dictionary of content --- ##

SECTIONS = [
    "objectives",
    "intro",
    "syntax",
    "files",
    "help",
    "file-handling",
    "wildcards",
    "redirection-pipes-filters"
    # "loops",
    #"print",
    # "file-naming",
    # "quotes",
    # "history",
    # "keyboard",
    # "scripts",
    # "find-regex",
    # "practice",
    # "recap",
    # "acknowledgement",
    # "cheatsheet"
    ]

## --- Build Rules --- ##

rule buildSlides:
    input:
        styleFile = "beamerthemeLagonBleu.sty",
        latexPreamble = "preamble.tex",
        biblio = "refs.bib",
        bibclass = "chicago.csl",
        logo = "figures/logo/by-nc-sa-ccLicense.eps",
        #figures = expand("figures/{iFigure}",      iFigure  = FIGURES),
        metaData = "slideConfig.yaml",
        section = expand("sections/{iSection}.md",  iSection = SECTIONS)
    output:
        OUTPUT
    shell:
        "pandoc -t beamer -H preamble.tex \
            {input.metaData} \
            {input.section} \
            --filter pandoc-citeproc \
            --slide-level 2 \
            {PDF_ENGINE} \
            --highlight-style zenburn \
            --bibliography={input.biblio} \
            -o {output}"

rule pdfclean:
    shell:
        "rm {OUTPUT}"
